services:
    bigz_halapi.url_generator:
        class: Halapi\UrlGenerator\SymfonyUrlGenerator
        arguments: ["@router"]
    bigz_halapi.object_manager:
        class: bigz\halapi\ObjectManager\DoctrineOrmObjectManager
        arguments: ["@doctrine.orm.entity_manager"]

    bigz_halapi.links_relation:
        class: bigz\halapi\Relation\LinksRelation
        arguments: ["@annotation_reader", "&bigz_halapi@url_generator", "@bigz_halapi.object_manager"]
    bigz_halapi.embedded_relation:
        class: bigz\halapi\Relation\EmbeddedRelation
        arguments: ["@annotation_reader", "@request_stack"]

    bigz_halapi.relation_factory:
        class: bigz\halapi\Factory\RelationFactory
        arguments: [["@bigz_halapi.embedded_relation", "@bigz_halapi.links_relation"]]

    bigz_halapi.pagination_factory:
        class: bigz\halapi\Factory\PaginationFactory
        arguments: ["@router", "@bigz_halapi.object_manager", "@request_stack"]

    bigz_halapi.json_event_subscriber:
        class: bigz\halapi\Subscriber\JsonEventSubscriber
        arguments: ["@bigz_halapi.relation_factory"]
        tags:
            - { name: jms_serializer.event_subscriber }
