services:
    bigz_halapi.url_generator:
        class: Halapi\UrlGenerator\SymfonyUrlGenerator
        arguments: ["@router"]
    bigz_halapi.object_manager:
        class: Halapi\ObjectManager\DoctrineOrmObjectManager
        arguments: ["@doctrine.orm.entity_manager"]
    bigz_halapi.pager:
        class: Halapi\Pager\PagerFanta
        arguments: ["DoctrineORM"]
    bigz_halapi.request_factory:
        class: Bigz\HalapiBundle\Factory\RequestFactory
    bigz_halapi.request:
        class: Psr\Http\Message\ServerRequestInterface
        factory: 'bigz_halapi.request_factory:getRequest'
        arguments: ['@request_stack']
    bigz_halapi.reader:
        class: Halapi\AnnotationReader\DoctrineAnnotationReader
        arguments: ['@annotation_reader']

    bigz_halapi.links_relation:
        class: Halapi\Relation\LinksRelation
        arguments: ["@bigz_halapi.reader", "@bigz_halapi.url_generator", "@bigz_halapi.object_manager"]
    bigz_halapi.embedded_relation:
        class: Halapi\Relation\EmbeddedRelation
        arguments: ["@bigz_halapi.reader", "@bigz_halapi.request"]

    bigz_halapi.relation_factory:
        class: Halapi\Factory\RelationFactory
        arguments: [["@bigz_halapi.embedded_relation", "@bigz_halapi.links_relation"]]

    bigz_halapi.pagination_factory:
        class: Halapi\Factory\PaginationFactory
        arguments:
          - "@bigz_halapi.url_generator"
          - "@bigz_halapi.object_manager"
          - "@bigz_halapi.request"
          - "@bigz_halapi.pager"
          - "@bigz_halapi.reader"

    bigz_halapi.json_event_subscriber:
        class: Halapi\Subscriber\JsonEventSubscriber
        arguments: ["@bigz_halapi.relation_factory"]
        tags:
            - { name: jms_serializer.event_subscriber }
