services:
    Bigz_halapi.url_generator:
        class: Halapi\UrlGenerator\SymfonyUrlGenerator
        arguments: ["@router"]
    Bigz_halapi.object_manager:
        class: Halapi\ObjectManager\DoctrineOrmObjectManager
        arguments: ["@doctrine.orm.entity_manager"]

    Bigz_halapi.links_relation:
        class: Halapi\Relation\LinksRelation
        arguments: ["@annotation_reader", "&Bigz_halapi@url_generator", "@Bigz_halapi.object_manager"]
    Bigz_halapi.embedded_relation:
        class: Halapi\Relation\EmbeddedRelation
        arguments: ["@annotation_reader", "@request_stack"]

    Bigz_halapi.relation_factory:
        class: Halapi\Factory\RelationFactory
        arguments: [["@Bigz_halapi.embedded_relation", "@Bigz_halapi.links_relation"]]

    Bigz_halapi.pagination_factory:
        class: Halapi\Factory\PaginationFactory
        arguments: ["@router", "@Bigz_halapi.object_manager", "@request_stack"]

    Bigz_halapi.json_event_subscriber:
        class: Halapi\Subscriber\JsonEventSubscriber
        arguments: ["@Bigz_halapi.relation_factory"]
        tags:
            - { name: jms_serializer.event_subscriber }
